[package]
name = "create-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
jsonwebtoken = "9.3.0"
serde_json = "1.0.116"
